### ISSUE TITLE
AttributeError - openai.api_base

### ISSUE THREAD

**Issue by MattMcDowall** [DakeZhang1998/ReadProbe#2]
I've set up the streamlit app according to the instructions, including adding my keys in the Secrets settings. The Secrets setting looks like:
`[azure_open_ai]`
`key = '<my azure key>'`
`[openai_keys]`
`key = '<my openai key>'`
`[google_forms]`
`link = '<my Google form link>'`

But when I try to start the app, I get the following error:
`KeyError: 'azure_openai'`
`During handling of the above exception, another exception occurred:`
`File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script`
`    exec(code, module.__dict__)`
`File "/app/readprobe/main.py", line 22, in <module>`
`    openai.api_base = st.secrets.azure_openai.api_base`
`File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 296, in __getattr__`
`    raise AttributeError(_missing_attr_error_message(key))`
`AttributeError: st.secrets has no attribute "azure_openai". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management`

I tried changing the key name in Secrets from `key` to `azure_openai`, but it didn't help.

**Comment by MattMcDowall** [comment]
Got it to work. Had to change my Secrets settings to:
`azure_openai.api_base = 'https://api.bing.microsoft.com/' # "Endpoint" from Azure's Keys and Endpoint page`
`azure_openai.api_key = '<my azure key>'`
`[openai_keys]`
`key = '<my openai key>'`
`[google_forms]`
`link = '<my Google form link>'`

**Comment by DakeZhang1998** [comment]
Glad you figured it out! I was writing my reply just now. 😊

**Comment by MattMcDowall** [comment]
Actually I'm still not sure I've got it. It lets me run a probe now, but then returns an error: `openai.error.InvalidRequestError: Resource not found`

I can paste in the full error text, if it's helpful. But I suspect this has to do with what I've used for my api_base. Does the simple `https://api.bing.microsoft.com/` look right to you, for that?

**Comment by DakeZhang1998** [comment]
For the ChatGPT service, are you using Azure APIs or OpenAI APIs?

**Comment by MattMcDowall** [comment]
I didn't change it, so it's set to Azure.

**Comment by DakeZhang1998** [comment]
OK. So for Azure OpenAI services, it is a bit complicated. It should be something like:
```
[azure_openai]
api_base = 'https://[your_project_name].openai.azure.com/'
api_key = 'XXXXXXXXXX'
```
This document might be helpful: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-studio.
Not sure what the current situation is. But several months ago, I needed to submit an application to access this service. If you have credits on the OpenAI platform, it would be much easier to use their APIs.

**Comment by MattMcDowall** [comment]
I do have credits, and I've switched it now, but I'm getting different errors there. What should that section look like?

**Comment by DakeZhang1998** [comment]
```
[openai_keys]
key = 'XXXXXXX'
```
